// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_entropy
NumericVector rcpp_entropy(NumericVector xs);
RcppExport SEXP cRomppass_rcpp_entropy(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    __result = Rcpp::wrap(rcpp_entropy(xs));
    return __result;
END_RCPP
}
// normalize_wd
NumericVector normalize_wd(NumericVector xs, double norm_factor);
RcppExport SEXP cRomppass_normalize_wd(SEXP xsSEXP, SEXP norm_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< double >::type norm_factor(norm_factorSEXP);
    __result = Rcpp::wrap(normalize_wd(xs, norm_factor));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP cRomppass_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
