# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_entropy <- function(xs) {
    .Call('cRomppass_rcpp_entropy', PACKAGE = 'cRomppass', xs)
}

rcpp_hello_world <- function() {
    .Call('cRomppass_rcpp_hello_world', PACKAGE = 'cRomppass')
}

